import tiktoken, json, sys

enc = tiktoken.get_encoding("gpt2")
cases = [
    "hello world",
    " hello",
    "don't",
    "they're",
    "2024",
    "café",
    "\n",
    "\t",
    "   ",
    "aaaaaaaa",
    "",
    "<|endoftext|>",
]
result = [{"in": c, "out": enc.encode(c, allowed_special="all")} for c in cases]

if len(sys.argv) > 1:
    def zig_string(s):
        """Emit a Zig string literal. Uses \\ strings (no escaping) where possible,
        falls back to "..." for chars that can't live in a \\ string (\n, \t, \r)."""
        if s == "":
            return '""'
        if "\n" in s or "\t" in s or "\r" in s:
            esc = s.replace("\\", "\\\\").replace('"', '\\"') \
                   .replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
            return f'"{esc}"'
        return f"\\\\{s}"

    lines = [
        "// Auto-generated by gen_tokenizer_golden.py — do not edit",
        "pub const Case = struct { in: []const u8, out: []const u32 };",
        "pub const cases: []const Case = &.{",
    ]
    for case in result:
        s, ids = case["in"], case["out"]
        in_lit = zig_string(s)
        ids_lit = ", ".join(str(x) for x in ids)
        out_lit = f"&.{{ {ids_lit} }}" if ids else "&.{}"
        # \\ strings capture to EOL, so .out must start on the next line
        lines.append(f"    .{{ .in = {in_lit}")
        lines.append(f"    , .out = {out_lit} }},")
    lines.append("};")

    with open(sys.argv[1], "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
else:
    print(json.dumps(result, ensure_ascii=False, indent=2))
