"""
Helpers for emitting Zig literals from Python values.
Each function takes a Python value and returns a Zig source string.
"""

import struct


def header(generator: str) -> str:
    return f"// Auto-generated by {generator} — do not edit"


def string(s: str) -> str:
    """Zig string literal. Uses \\\\ multiline form when safe, falls back to escaped "..."."""
    if s == "":
        return '""'
    if "\n" in s or "\t" in s or "\r" in s:
        esc = (s.replace("\\", "\\\\")
                .replace('"', '\\"')
                .replace("\n", "\\n")
                .replace("\t", "\\t")
                .replace("\r", "\\r"))
        return f'"{esc}"'
    return f"\\\\{s}"


def f32_bits(v: float) -> str:
    """u32 hex literal holding the exact IEEE-754 single-precision bits of v."""
    bits = struct.unpack("<I", struct.pack("<f", v))[0]
    return f"0x{bits:08X}"


def f32_bits_array(values) -> str:
    """Inline .{ 0x..., ... } array initializer of u32 f32 bit patterns."""
    return ".{ " + ", ".join(f32_bits(v) for v in values) + " }"


def u32_slice(values) -> str:
    """&.{ 1, 2, 3 } inline []const u32 slice literal, or &.{} for empty."""
    if not values:
        return "&.{}"
    return "&.{ " + ", ".join(str(v) for v in values) + " }"


def padded_shape(dims, max_rank: int = 4) -> str:
    """Fixed [max_rank]u32 init with zero-padding: .{ d0, d1, 0, 0 }"""
    padded = list(dims) + [0] * (max_rank - len(dims))
    return ".{ " + ", ".join(str(d) for d in padded) + " }"
